--- 
apiVersion: v1
kind: Pod
metadata: 
  name: probes
spec: 
  containers: 
    - 
      args: 
        - ./probes
        - "5"
      image: "us.icr.io/order-mgmt-np/oms/probes:v1"
      name: readiness
      readinessProbe: 
        failureThreshold: 1
        httpGet: 
          path: /
          port: 80
          scheme: HTTP
        initialDelaySeconds: 60
        periodSeconds: 10
        successThreshold: 1
        timeoutSeconds: 1

